spring:
  datasource:
    url: jdbc:mysql://121.36.77.21:5019/noctuid?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: dfq5019.
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      validation-timeout: 250
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #devtools:
    #restart:
      #enabled: true  #设置开启热部署
      #additional-paths: src/main/java #重启目录
      #exclude: WEB-INF/**
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

debug: false
logging:
  pattern:
    console: "%-5level %logger{50} - %msg%n"
  register-shutdown-hook: false
  level:
    root: info



